development:
  adapter: postgresql
  encoding: unicode
  database: ash_blog_dev
  pool: 5
  username: erolerturk
  password:

# test:
#   adapter: postgresql
#   encoding: unicode
#   database: kre_test
#   pool: 5
#   username: erolerturk
#   password:

# production:
#   adapter: postgresql
#   encoding: unicode
#   database: kre_production
#   pool: 5
#   username: erolerturk
#   password: